version: '3.9'

services:
  probe_server:
    image: probe-22-server
    build:
      context: .
      dockerfile: Dockerfile
      target: ${TARGET}
    restart: always
    ports:
      - ${SERVER_EXTERNAL_PORT}:3000
    depends_on:
      - probe_db
    volumes:
      - .:/app

  probe_db:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ./pg_db:/data/postgres

  authadminer:
    container_name: "adminer_authdb"
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
